let post = [
  {
    image: 'https://s.mxmcdn.net/images-storage/albums4/9/9/8/2/5/1/35152899_800_800.jpg',
    imageText: 'Mullally - Wonderful',
    backBtnType: 'w',
    content: [
      {
        type: 'text',
        data: "Provided to YouTube by TuneCore" +
          "\nWonderful · Mullally" +
          "\nWonderful" +
          "\n℗ 2016 Black Diamond Music" +
          "\nReleased on: 2016-09-20" +
          "\nAuto-generated by YouTube.",
        desc: ''
      },
      {
        type: 'youtube',
        data: "vD6-JQtsmas",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=vD6-JQtsmas',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 9. 30'
  },
  {
    image: 'https://images.genius.com/cbf4cda8ca81f86c154d3f917eb23d5a.320x320x1.jpg',
    imageText: 'Johnny Balik - Honey (Official Audio)',
    backBtnType: 'b',
    content: [
      {
        type: 'text',
        data: "'Honey' by Johnny Balik" +
          "\nOfficial Audio",
        desc: ''
      },
      {
        type: 'youtube',
        data: "8z-27EJcMxc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=8z-27EJcMxc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 1. 27'
  },
  {
    image: 'https://i.scdn.co/image/ab67616d0000b273432b785048e2a41ace93e3f1',
    imageText: 'Johnny Stimson - Gimme Gimme',
    backBtnType: 'w',
    content: [
      {
        type: 'text',
        data: "Provided to YouTube by Antifragile Music" +
          "\nGimme Gimme · Johnny Stimson" +
          "\nGimme Gimme" +
          "\n℗ 2018 AntiFragile Music" +
          "\nReleased on: 2018-06-29" +
          "\nMain  Artist: Johnny Stimson" +
          "\nAuto-generated by YouTube.'",
        desc: ''
      },
      {
        type: 'youtube',
        data: "PYrK90a5PQI",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=PYrK90a5PQI',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 2. 6'
  },
  {
    image: 'https://i.pinimg.com/564x/5d/a5/6c/5da56cd1e61c2241520ac619edcb92b4.jpg',
    imageText: 'Mullally - Sweet Coffee',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "kQOy1SmFuTs",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=kQOy1SmFuTs',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 2. 27'},
  {
    image: 'https://e-news.us/wp-content/uploads/2019/04/tr-jpg-92.jpg',
    imageText: 'Johnny Stimson - Flower',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "sgNkCrAhTGc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=sgNkCrAhTGc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 4. 5'
  },
  {
    image: 'https://i.ytimg.com/vi/CDBL_JjoC1M/maxresdefault.jpg',
    imageText: 'RINI - Oceane ft. Olivia Escuyos',
    backBtnType: 'w',
    content: [
      {
        type: 'text',
        data: 'Oceane\nTrack 5/5 from After The Sun EP',
        desc: ''
      },
      {
        type: 'youtube',
        data: "CDBL_JjoC1M",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=CDBL_JjoC1M',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 11. 4'
  },
  {
    image: 'https://phinf.pstatic.net/tvcast/20200314_277/i0M9g_1584115908973rkDYr_JPEG/B120196068_EPI0003_31_B.jpg',
    imageText: '45RPM - YOU & ME Feat. gong (공)',
    backBtnType: 'w',
    content: [
      {
        type: 'text',
        data: "Provided to YouTube by Genie Music Corporation" +
          "\nYOU & ME (Feat. gong (공)) · 45알피엠 (45RPM)" +
          "\n너희가 힙합을 아느냐 Do you know Hip-Hop Episode 2" +
          "\n℗ 2020 Stone Music Entertainment" +
          "\nReleased on: 2020-03-14" +
          "\nAuto-generated by YouTube.",
        desc: ''
      },
      {
        type: 'youtube',
        data: "sFTogDCxFWM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=sFTogDCxFWM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 3. 14'
  },
  {
    image: 'https://i.ytimg.com/vi/MY7CFJuBrIs/0.jpg?imageType=video',
    imageText: 'Easy Life - Dead Celebrities',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "MY7CFJuBrIs",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=MY7CFJuBrIs',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 1. 9'
  },
  {
    image: 'https://t2.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/27PV/image/B2SaAFuPl0vT-4UReK5s1TLTupU.jpg',
    imageText: 'HONNE - Day 1',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "hWOB5QYcmh0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=hWOB5QYcmh0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 3. 29'
  },
  {
    image: 'https://i.ytimg.com/vi/SB4Jra4zR80/maxresdefault.jpg',
    imageText: 'HONNE - Me & You',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "SB4Jra4zR80",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=SB4Jra4zR80',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 4. 27'
  },
  {
    image: 'https://t1.daumcdn.net/cfile/tistory/2502D1405833797716',
    imageText: "Ella Mai - She Don't Ft. TyDolla$ign [Official Video]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "sg34LyfYobo",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=sg34LyfYobo',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 2. 15'
  },
  {
    image: 'https://www.rollingstone.com/wp-content/uploads/2018/06/watch-ella-mai-music-video-for-bood-up-1-1a5ad85f-75e5-4b9e-9dff-2a0757cbd17b.jpg?resize=1800,1200&w=1800',
    imageText: "Ella Mai - Boo'd Up",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "6YNZlXfW6Ho",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=6YNZlXfW6Ho',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 4. 26'
  },
  {
    image: 'https://i1.sndcdn.com/artworks-000416094345-srl41o-t500x500.jpg',
    imageText: 'Finding Hope - JDS (Fantasy)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "c0vYMEuoLVs",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=c0vYMEuoLVs',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 4. 8'
  },
  {
    image: 'https://i.ytimg.com/vi/W7O03rIvP3w/maxresdefault.jpg',
    imageText: 'Christian Kuria - Too Good [Official Audio]',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "W7O03rIvP3w",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=W7O03rIvP3w',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 12. 29'
  },
  {
    image: 'https://i.ytimg.com/vi/RfgL_OaTomc/maxresdefault.jpg',
    imageText: 'Samm Henshaw - Doubt (Official Video) ft. Wretch 32',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "RfgL_OaTomc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=RfgL_OaTomc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 10. 4'
  },
  {
    image: 'https://i.ytimg.com/vi/M_N2TA6Xjdo/maxresdefault.jpg',
    imageText: 'Etham - 12:45',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "GhWnG7YhcEE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=GhWnG7YhcEE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 11. 16'
  },
  {
    image: 'https://i.ytimg.com/vi/fHI8X4OXluQ/maxresdefault.jpg',
    imageText: 'The Weeknd - Blinding Lights',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "4NRXx6U8ABQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=4NRXx6U8ABQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 1. 22'
  },
  {
    image: 'https://i.ytimg.com/vi/ghuXuZAocqE/maxresdefault.jpg',
    imageText: 'Tom Misch - Sunshine',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "ghuXuZAocqE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=ghuXuZAocqE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2015. 7. 3'
  },
  {
    image: 'https://i.ytimg.com/vi/5Z-CKNYzV6g/maxresdefault.jpg',
    imageText: 'Lauv - Paris in the Rain [Official Video]',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "kOCkne-Bku4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=kOCkne-Bku4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 11. 17'
  },
  {
    image: 'https://i.ytimg.com/vi/b_jd9l91KdM/maxresdefault.jpg',
    imageText: 'Emily King - Distance',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "DjxvOfn7rLc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=DjxvOfn7rLc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2015. 11. 15'
  },
  {
    image: 'https://i.ytimg.com/vi/rtlq3yiFw6Y/hqdefault.jpg',
    imageText: "죠지 (George) - Let's Go Picnic",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "k3XhvM5OcYQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=k3XhvM5OcYQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 2. 26'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/081/304/052/81304052_1573174242526_1_600x600.JPG',
    imageText: 'Pink Sweat$ - Honesty (Official Music Video)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "-Y9VtoPvtuM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=-Y9VtoPvtuM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 9. 27'
  },
  {
    image: 'https://i.ytimg.com/vi/kwnUj8iSrA8/maxresdefault.jpg',
    imageText: 'jeebanoff(지바노프) - We (OUI) (feat. sogumm)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "cVy4eJyD3yQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=cVy4eJyD3yQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 4. 11'
  },
  {
    image: 'https://images.genius.com/e9bc185c154aa5abbf64fb320a8c8c09.600x600x1.jpg',
    imageText: 'Schwey - Elasto',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "cMH3jz8RefE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=cMH3jz8RefE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 3. 14'
  },
  {
    image: 'https://i.ytimg.com/vi/MINlN-294DU/hqdefault.jpg',
    imageText: 'THAMA - Questions (Feat. 주영 Joo Young)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "MINlN-294DU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=MINlN-294DU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 3. 20'
  },
  {
    image: 'https://t1.daumcdn.net/cfile/tistory/997AE43B5B37380A33',
    imageText: '백예린- LaLaLa Love Song (With. Retro anime)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "l61rMqqFU3g",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=l61rMqqFU3g',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 2. 23'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/081/033/654/81033654_1518513634837_1_600x600.JPG',
    imageText: 'Justine Skye - Know Myself ft.Vory',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "pnpa4cyy6iE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=pnpa4cyy6iE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 7. 25'
  },
  {
    image: 'https://i.ytimg.com/vi/unxxm3Q6Ob8/maxresdefault.jpg',
    imageText: 'PREP - Line By Line feat. Cory Wong & Paul Jackson jr',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "unxxm3Q6Ob8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=unxxm3Q6Ob8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 11. 11'
  },
  {
    image: 'https://i1.sndcdn.com/artworks-000170863668-qhwyds-t500x500.jpg',
    imageText: 'Jeff Bernat - Call You Mine (feat. Geologic Of The Blue Scholars)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "mKy2LUvdE5w",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=mKy2LUvdE5w',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 25'
  },
  {
    image: 'https://i1.sndcdn.com/artworks-000572954039-jia89r-t500x500.jpg',
    imageText: "Jeremy Passion & Melissa Polinar & Gabe Bondoc - Lemonade",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "KwrCpfD-Cwo",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=KwrCpfD-Cwo',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 27'
  },
  {
    image: 'https://i.ytimg.com/vi/607ENLoiRf0/hqdefault.jpg',
    imageText: 'Hamzaa - Sunday Morning (Official Music Video)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "YXcKDbSe80w",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=YXcKDbSe80w',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 17'
  },
  {
    image: 'https://i.ytimg.com/vi/jFBBCofvg8c/maxresdefault.jpg',
    imageText: 'Jeremy Passion - 32',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "jFBBCofvg8c",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=jFBBCofvg8c',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2014. 5. 10'
  },
  {
    image: 'https://image.bugsm.co.kr/album/images/500/4946/494629.jpg',
    imageText: '이문세 - 봄바람 (feat. 나얼)',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "smVvQVCtka4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=smVvQVCtka4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2015. 4. 7'
  },
  {
    image: 'https://www.lukasgraham.com/sites/g/files/g2000005361/f/201604/12918613_1034019863339241_982674834_n.jpg%3Fig_cache_key%3DMTIyMzI5MjE4MTA5NDk1MDc0Nw%253D%253D.2',
    imageText: 'Lukas Graham - Drunk In The Morning [Official Music Video ]',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "-yvHqenLpUU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=-yvHqenLpUU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 3. 16'
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Lukas_Graham_Youre_Not_There.jpg',
    imageText: "Lukas Graham - You're Not There [OFFICIAL MUSIC VIDEO]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "IC-bSbXZBcU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=IC-bSbXZBcU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 11. 5'
  },
  {
    image: 'https://i.pinimg.com/564x/72/8a/b7/728ab735f3f7b7877927503d9e231fa5.jpg',
    imageText: '죠지 - aura (feat. Sam Kim)',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "Sli1g5zlYIE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=Sli1g5zlYIE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 10. 3'
  },
  {
    image: 'https://i.ytimg.com/vi/Pzq_-YNCPNQ/maxresdefault.jpg',
    imageText: 'JAE JIN - Running (Acoustic) (Official Audio)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "Pzq_-YNCPNQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=Pzq_-YNCPNQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 2. 10'
  },
  {
    image: 'https://i.ytimg.com/vi/hlsqsIW6gx8/maxresdefault.jpg',
    imageText: "Adikara Fardy – Just The Two of Us (cover)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "hlsqsIW6gx8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=hlsqsIW6gx8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 1. 7'
  },
  {
    image: 'https://i.ytimg.com/vi/EcF237i-0U0/maxresdefault.jpg',
    imageText: "Brother Stone & The Get Down - 'How Deep Is Your Love' - Bee Gees (Cover)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "EcF237i-0U0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=EcF237i-0U0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 12. 12'
  },
  {
    image: 'https://i.ytimg.com/vi/URTtLCNoHXU/maxresdefault.jpg',
    imageText: 'Justin Timberlake - Midnight Summer Jam',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "URTtLCNoHXU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=URTtLCNoHXU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 2. 1'
  },
  {
    image: 'https://i1.sndcdn.com/artworks-000045460673-qz6mua-t500x500.jpg',
    imageText: 'Justin Timberlake - Let the Groove Get In',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "K8JyRko65L8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=K8JyRko65L8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 2. 18'
  },
  {
    image: 'https://d2tml28x3t0b85.cloudfront.net/tracks/audio/original_artwork/566aa680160f11e7a9cda7ecdff376cb/579f07d0160f11e7b604d74dfdc458fe.jpg',
    imageText: 'Calvin Harris - Heatstroke (Audio) ft. Young Thug, Ariana Grande, Pharrell Williams',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "ME9x1mSNv-w",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=ME9x1mSNv-w',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 6. 30'
  },
  {
    image: 'https://i.ytimg.com/vi/EtogCD8T83M/maxresdefault.jpg',
    imageText: "죠지 - 바라봐줘요",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "U8XHwiMOyWQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=U8XHwiMOyWQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 2. 11'
  },
  {
    image: 'https://i.ytimg.com/vi/3z9sq9e5iu4/maxresdefault.jpg',
    imageText: 'BIBI(비비) _ BINU(비누)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "3z9sq9e5iu4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=3z9sq9e5iu4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 5. 15'
  },
  {
    image: 'https://i.ytimg.com/vi/WSg9TPYIuxU/hqdefault.jpg',
    imageText: '40(포티) - 이불',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "4YTKUZHJEhI",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=4YTKUZHJEhI',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 2. 28'
  },
  {
    image: 'https://i.ytimg.com/vi/1t6uA9Hvu40/maxresdefault.jpg',
    imageText: "Gabe Bondoc – 'Gentlemen Don't",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "1t6uA9Hvu40",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=1t6uA9Hvu40',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 3. 3'
  },
  {
    image: 'https://www.maifm.co.nz/home/hip-hop-hollywood/2016/08/lauryn-hill-covers-jammin----master-blaster/_jcr_content/image.dynimg.1280.q75.jpg/v1470720122161/lauryn-hill.jpg',
    imageText: "Ms. Lauryn Hill 'Jammin/Master Blaster'",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "Yh5usm9WfJw",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=Yh5usm9WfJw',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 8. 5'
  },
  {
    image: 'https://www.rap-up.com/app/uploads/2011/06/hill-fallon-1280x720.jpg',
    imageText: 'Lauryn Hill "Doo Wop (That Thing)"',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "4B4qEjqVM7o",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=4B4qEjqVM7o',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2011. 8. 11'
  },
  {
    image: 'https://i.ytimg.com/vi/sY1-OPsqJj0/maxresdefault.jpg',
    imageText: '박정현(Lena Park) - 오랜만에(Acoustic Ver)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "sY1-OPsqJj0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=sY1-OPsqJj0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2013. 5. 27'
  },
  {
    image: 'https://i.ytimg.com/vi/NaxgH0yoeK8/maxresdefault.jpg',
    imageText: '박정현 - 미아',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "NaxgH0yoeK8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=NaxgH0yoeK8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2013. 1. 10'
  },
  {
    image: 'https://i.ytimg.com/vi/m87vQBwgGo8/maxresdefault.jpg',
    imageText: 'Sam Smith - Baby, You Make Me Crazy (Acoustic)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "m87vQBwgGo8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=m87vQBwgGo8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 6. 21'
  },
  {
    image: 'https://i.ytimg.com/vi/1LStVaYdK4M/maxresdefault.jpg',
    imageText: 'Sam Smith - Too Good At Goodbyes (Official Video)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "J_ub7Etch2U",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=J_ub7Etch2U',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 9. 18'
  },
  {
    image: 'https://i.ytimg.com/vi/CwfoyVa980U/hqdefault.jpg',
    imageText: "Charlie Puth - 'How Long' [Official Video]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "CwfoyVa980U",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=CwfoyVa980U',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 10. 20'
  },
  {
    image: 'https://img.discogs.com/FGvbx4VHCdwHIMX1I7Is4p4vWSM=/fit-in/500x500/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8747173-1471189526-1755.jpeg.jpg',
    imageText: 'Michael Jackson - Rock With You (The Reflex Revision)',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "TWes186orLA",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=TWes186orLA',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 1. 5'
  },
  {
    image: 'https://i.ytimg.com/vi/3zrSoHgAAWo/hqdefault.jpg',
    imageText: 'Chet Baker - I fall in love too easily',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "3zrSoHgAAWo",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=3zrSoHgAAWo',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2009. 2. 16'
  },
  {
    image: 'https://i.ytimg.com/vi/PcmfjqzJVQ0/hqdefault.jpg',
    imageText: "Billy griffin - hold me tighter in the rain",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "nRXV7dHRWIU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=nRXV7dHRWIU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 1. 26'
  },
  {
    image: 'https://i.pinimg.com/originals/47/42/0e/47420e9b8af16a732ab5ba8a08c9f28b.jpg',
    imageText: "Earth, Wind & Fire ft The Emotions ~ Boogie Wonderland 1979 Disco Purrfection Version",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "xGfoY4nno3A",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=xGfoY4nno3A',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2015. 12. 19'
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Lovemachine.jpg',
    imageText: 'the miracles - Love machine',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "qQi_9PmhNW0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=qQi_9PmhNW0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 7. 31'
  },
  {
    image: 'https://i.ytimg.com/vi/h73T-J3XCDE/hqdefault.jpg',
    imageText: 'Justin timberlake - Until The End Of Time',
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "xEB2nZJ3ynY",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=xEB2nZJ3ynY',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 1. 26'
  },
  {
    image: 'https://i.ytimg.com/vi/vpfSfddhmT4/maxresdefault.jpg',
    imageText: '쌈디 - 귀가본능 (feat. JINBO the superfreak)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "vpfSfddhmT4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=vpfSfddhmT4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 6. 18'
  },
  {
    image: 'https://images.genius.com/4516dfbbb080dd9257db2fc92b139e0e.1000x1000x1.jpg',
    imageText: 'JAY PARK - Baddest Nice Guys (Feat. 사이먼 도미닉 Simon Dominic, DJ Light, DJ Wegun)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "lPJgYYucnGw",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=lPJgYYucnGw',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 8. 5'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/080/961/670/80961670_1498800654830_1_600x600.JPG',
    imageText: '창모 - I always',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "dmr-nKZKewY",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=dmr-nKZKewY',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 7. 15'
  },
  {
    image: 'https://i.ytimg.com/vi/mFhw4AIlRjM/maxresdefault.jpg',
    imageText: "비워 (Beer) (Prod. Way Ched)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "ZViFTZa-ocw",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=ZViFTZa-ocw',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 6. 28'
  },
  {
    image: 'https://i.ytimg.com/vi/KK-1xrOsqXI/maxresdefault.jpg',
    imageText: '한동근 - 미치고 싶다',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "KK-1xrOsqXI",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=KK-1xrOsqXI',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 5. 5'
  },
  {
    image: 'https://i.ytimg.com/vi/JkTx6HdZ6eA/maxresdefault.jpg',
    imageText: 'Yoon Mi Rae (윤미래) - Say',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "uO_j23R18cM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=uO_j23R18cM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 2. 22'
  },
  {
    image: 'https://i.ytimg.com/vi/5orrZxSjLQA/hqdefault.jpg',
    imageText: 'Charlie Puth - The Way I Am',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "EQnk-h-LCpQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=EQnk-h-LCpQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 7. 9'
  },
  {
    image: 'https://scontent-yyz1-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/72725666_935390136860474_2810627684568422566_n.jpg?_nc_ht=scontent-yyz1-1.cdninstagram.com&_nc_cat=102&_nc_ohc=Gzuvy42PURoAX-qkCnH&oh=c1dd8368f578f5310c8b69d38e8c0c86&oe=5EBF97A2',
    imageText: '박정현 - 까만 일기장 (비긴어게인3)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "rlU7CMsglvY",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=rlU7CMsglvY',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 3. 23'
  },
  {
    image: 'https://i.ytimg.com/vi/XXx6RDzR6eM/maxresdefault.jpg',
    imageText: "Al Green - Let's Stay Together",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "COiIC3A0ROM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=COiIC3A0ROM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2009. 9. 20'
  },
  {
    image: 'https://i.ytimg.com/vi/bEeaS6fuUoA/maxresdefault.jpg',
    imageText: "Bill Withers - Lovely Day",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "COiIC3A0ROM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=COiIC3A0ROM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2009. 9. 20'
  },
  {
    image: 'https://live.staticflickr.com/2851/9432195460_bb614634df_b.jpg',
    imageText: "Bruno mars - Treasure",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "jz7C2W4m26U",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=jz7C2W4m26U',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2015. 4. 4'
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/Show_And_Tell_-_Al_Wilson.jpg/220px-Show_And_Tell_-_Al_Wilson.jpg',
    imageText: "Al Wilson - Show And Tell",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "ItgAlRuafaU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=ItgAlRuafaU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2010. 4. 3'
  },
  {
    image: 'https://i.pinimg.com/564x/15/73/4b/15734b795ad98ce48d9985ad21e539da.jpg',
    imageText: "In Performance at The White House | Justin Timberlake | (Sittin' On) The Dock Of The Bay",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "tIx6_Z5v88k",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=tIx6_Z5v88k',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2013. 4. 17'
  },
  {
    image: 'https://i.ytimg.com/vi/4pZlFDQ1N2E/hqdefault.jpg',
    imageText: "Jamie Foxx - I Got a Woman (The Jonathan Ross Show)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "4pZlFDQ1N2E",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=4pZlFDQ1N2E',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2013. 1. 13'
  },
  {
    image: 'https://img.discogs.com/Lf84DdWwdU_LOtKMXVbl7fiwfL8=/fit-in/568x574/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1918469-1252398548.jpeg.jpg',
    imageText: "Ray Charles - Georgia On My Mind (Live)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "qIp9TwSEgFg",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=qIp9TwSEgFg',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 11. 8'
  },
  {
    image: 'https://i.ytimg.com/vi/CzAkTrDiXxg/maxresdefault.jpg',
    imageText: "Ray Charles - Song For You (Live at Montreux 1997)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "CzAkTrDiXxg",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=CzAkTrDiXxg',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 7. 13'
  },
  {
    image: 'https://i.ytimg.com/vi/cyNBNLujyHE/hqdefault.jpg',
    imageText: "Colde - 없어도 돼",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "cyNBNLujyHE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=cyNBNLujyHE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 5. 31'
  },
  {
    image: 'https://i.ytimg.com/vi/2OEdoFGp140/maxresdefault.jpg',
    imageText: "Crush - Ibiza",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "2OEdoFGp140",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=2OEdoFGp140',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 1. 23'
  },
  {
    image: 'https://i.ytimg.com/vi/7EDijfvY7do/hqdefault.jpg',
    imageText: "Colde (콜드) - 향",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "7EDijfvY7do",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=7EDijfvY7do',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 5. 31'
  },
  {
    image: 'https://i.ytimg.com/vi/oCtYekG1qBc/maxresdefault.jpg',
    imageText: "Bruno mars - All i ask (covers Adele's)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "oCtYekG1qBc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=oCtYekG1qBc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 11. 3'
  },
  {
    image: 'https://images.genius.com/0338ebd2e5ddff1c6a801324940e69b9.1000x1000x1.jpg',
    imageText: "Alaina Castillo - just a boy",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "of7uskrKijc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=of7uskrKijc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 3. 26'
  },
  {
    image: 'https://i.vimeocdn.com/video/633858192.webp?mw=900&mh=506',
    imageText: "CIKI – Baby Crush",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "FDMxZWbmoIo",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=FDMxZWbmoIo',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 11. 29'
  },
  {
    image: 'https://i.ytimg.com/vi/pwzyWm_2qg4/maxresdefault.jpg',
    imageText: "Twelve - subway sandwich",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "pwzyWm_2qg4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=pwzyWm_2qg4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 2. 21'
  },
  {
    image: 'https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F9938D9375C88463926',
    imageText: "Charlie Puth - Done For Me (feat. Kehlani)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "TdyllLZeviY",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=TdyllLZeviY',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 4. 21'
  },
  {
    image: 'https://i.ytimg.com/vi/UsouvLWx9OA/hqdefault.jpg',
    imageText: "OuiOui (위위) - 알잖아 [Official Audio]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "UsouvLWx9OA",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=UsouvLWx9OA',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 5. 18'
  },
  {
    image: 'https://i.ytimg.com/vi/Q3XMtomYXac/maxresdefault.jpg',
    imageText: "OuiOui (위위) - 니 생각 (Thinkin' bout you) (Feat. Wilcox)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "2_zhV_9CGik",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=2_zhV_9CGik',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 11'
  },
  {
    image: 'https://i.ytimg.com/vi/mHc2A6KtV4o/maxresdefault.jpg',
    imageText: "OuiOui (위위) - 멀어지지 않게 (not too far)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "lyF7-GHQIsM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=lyF7-GHQIsM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 11'
  },
  {
    image: 'https://i.ytimg.com/vi/40UIWy1jMoQ/maxresdefault.jpg',
    imageText: "OuiOui (위위) - 만나러 갈게 (We'll Be Alright)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "40UIWy1jMoQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=40UIWy1jMoQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 1. 1'
  },
  {
    image: 'https://i.ytimg.com/vi/5hYLMnvN-Uc/maxresdefault.jpg',
    imageText: "OuiOui (위위) - Ocean",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "5hYLMnvN-Uc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=5hYLMnvN-Uc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 11'
  },
  {
    image: 'https://i.ytimg.com/vi/mHc2A6KtV4o/maxresdefault.jpg',
    imageText: "OuiOui (위위) - Maybe I",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "mHc2A6KtV4o",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=mHc2A6KtV4o',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 10. 28'
  },
  {
    image: 'https://i.ytimg.com/vi/JYcSJNkQSDI/maxresdefault.jpg',
    imageText: "다이나믹 듀오(Dynamicduo) - [OFF DUTY] 'Garage Live' 2/4 | Career High",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "JYcSJNkQSDI",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=JYcSJNkQSDI',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 17'
  },
  {
    image: 'https://i.ytimg.com/vi/FN-I9SBdFxs/maxresdefault.jpg',
    imageText: "다이나믹 듀오(Dynamicduo) - 맵고짜고단거 (Feat. 페노메코 Penomeco)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "am_A1Ojifks",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=am_A1Ojifks',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 26'
  },
  {
    image: 'https://i.ytimg.com/vi/z-eg-bBCQJM/maxresdefault.jpg',
    imageText: "Charlie Puth - Left Right Left [Official Audio]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "z-eg-bBCQJM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=z-eg-bBCQJM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 1. 29'
  },
  {
    image: 'https://cdn.indiepost.co.kr/uploads/images/2019/09/10/iTMiXx-700x463.jpeg',
    imageText: "Anne-Marie - 2002 (Lyrics)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "qxCCGcMC1Jk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=qxCCGcMC1Jk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 4. 20'
  },
  {
    image: 'https://i.ytimg.com/vi/Wmyrrq_sJVw/maxresdefault.jpg',
    imageText: "Clean Bandit - Rockabye (feat. Sean Paul & Anne-Marie) [Official Video]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "papuvlVeZg8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=papuvlVeZg8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 10. 21'
  },
  {
    image: 'https://i.ytimg.com/vi/0m9icI0AOhw/hqdefault.jpg',
    imageText: "Anne-Marie - Perfect To Me [Official Lyric Video]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "0m9icI0AOhw",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=0m9icI0AOhw',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 11. 8'
  },
  {
    image: 'https://i.pinimg.com/originals/d4/cd/b9/d4cdb94614c4ecbf2e780830fb153526.jpg',
    imageText: "Shawn Mendes, Camila Cabello - Señorita (lyrics)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "23k5062WrDw",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=23k5062WrDw',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 12'
  },
  {
    image: 'https://i.ytimg.com/vi/iKzRIweSBLA/hqdefault.jpg',
    imageText: "Ed Sheeran - Perfect [Official Lyric Video]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "iKzRIweSBLA",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=iKzRIweSBLA',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 9. 22'
  },
  {
    image: 'https://t1.daumcdn.net/cfile/tistory/211AD0365973FCDA0E',
    imageText: "Ed Sheeran - Thinking Out Loud [Official]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "WpyfrixXBqU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=WpyfrixXBqU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2014. 6. 18'
  },
  {
    image: 'https://i.ytimg.com/vi/kP830ceDwvc/maxresdefault.jpg',
    imageText: "Adele - Chasing Pavements (Live Royal Albert Hall)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "kP830ceDwvc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=kP830ceDwvc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2012. 4. 16'
  },
  {
    image: 'https://i.ytimg.com/vi/izsvmDPQUH4/hqdefault.jpg',
    imageText: "Brian McKnight - Nobody (Visual)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "izsvmDPQUH4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=izsvmDPQUH4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 3. 13'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/080/348/500/80348500_1365153870748_1_600x600.JPG',
    imageText: "Ever Forever Whenever - 곽윤찬 (with Brian McKnight)",
    backBtnType: 'b',
    content: [
      {
        type: 'youtube',
        data: "T9euVjIVl_Q",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=T9euVjIVl_Q',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2014. 8. 8'
  },
  {
    image: 'https://i.ytimg.com/vi/lA9-TQE3lTM/maxresdefault.jpg',
    imageText: "Coldplay - Cry Cry Cry (Lyric Video)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "hKTA4NpZIAQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=hKTA4NpZIAQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 22'
  },
  {
    image: 'https://i.ytimg.com/vi/8OgVs4N1Mkk/maxresdefault.jpg',
    imageText: "Coldplay - BrokEn (Lyric Video)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "8OgVs4N1Mkk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=8OgVs4N1Mkk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 22'
  },
  {
    image: 'https://i.ytimg.com/vi/j82L3pLjb_0/hqdefault.jpg',
    imageText: "Coldplay - NPR Music Tiny Desk Concert",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "j82L3pLjb_0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=j82L3pLjb_0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 3. 6'
  },
  {
    image: 'https://i.ytimg.com/vi/yqtCGojXEpM/hqdefault.jpg',
    imageText: 'IU(아이유) - Blueming(블루밍) Live',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "yqtCGojXEpM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=yqtCGojXEpM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 29'
  },
  {
    image: 'https://i.ytimg.com/vi/o4HJptPl6-k/hqdefault.jpg',
    imageText: 'BrownEyed Soul (브라운 아이드 소울) - 똑같다면',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "YKjjoTLQwis",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=YKjjoTLQwis',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 2. 1'
  },
  {
    image: 'https://i.ytimg.com/vi/kMRLzSQorK0/hqdefault.jpg',
    imageText: 'KIM DONG RYUL (김동률) - Reply',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "kMRLzSQorK0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=kMRLzSQorK0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 1. 11'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/081/021/191/81021191_1515653924081_1_600x600.JPG',
    imageText: '김동률 - Although We Say I Love You (사랑한다 말해도) (Feat. 이소라)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "L-smW5aa0vE",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=L-smW5aa0vE',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 1. 15'
  },
  {
    image: 'https://i.ytimg.com/vi/JLT8qOdpDPM/maxresdefault.jpg',
    imageText: '적재 - 별 보러 가자',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "TlaGDYbxnJk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=TlaGDYbxnJk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 2. 11'
  },
  {
    image: 'https://i.ytimg.com/vi/sB6UGX2YPjQ/hqdefault.jpg',
    imageText: '아이유 - 이 지금',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "8ykMyNHAdKk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=8ykMyNHAdKk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 4. 21'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/081/089/262/81089262_1532930994428_1_600x600.JPG',
    imageText: 'ZICO - SoulMate (feat. 아이유)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "VxWeZX4c4Jc",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=VxWeZX4c4Jc',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 7. 30'
  },
  {
    image: 'https://i.ytimg.com/vi/7gzody2MNMs/maxresdefault.jpg',
    imageText: '로꼬 - Still (남아있어) (feat.Crush)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "7gzody2MNMs",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=7gzody2MNMs',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 11. 9'
  },
  {
    image: 'https://i.ytimg.com/vi/KPOBo8c1Wt8/maxresdefault.jpg',
    imageText: '로꼬 - It Takes Time (시간이 들겠지) (Feat. Colde)',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "KPOBo8c1Wt8",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=KPOBo8c1Wt8',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 10. 10'
  },
  {
    image: 'https://i.ytimg.com/vi/Mmr2EshzMgk/maxresdefault.jpg',
    imageText: '로꼬 - Party Band (Feat. PUNCHNELLO, Thur) + OPPA',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "Mmr2EshzMgk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=Mmr2EshzMgk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 5. 4'
  },
  {
    image: 'https://i.ytimg.com/vi/EwWUKX2wR1I/maxresdefault.jpg',
    imageText: 'Brian McKnight - Neva Get Enuf Of U',
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "BF_26dVxXqQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=BF_26dVxXqQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 1'
  },
  {
    image: 'https://i.ytimg.com/vi/zD6MVCwI5jo/maxresdefault.jpg',
    imageText: "Joe - I'd Rather Have A Love (Last.fm Sessions)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "1AIGEMl2mUI",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=1AIGEMl2mUI',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2013. 7. 30'
  },
  {
    image: 'https://i.ytimg.com/vi/_Bm14Bv1DKU/maxresdefault.jpg',
    imageText: "Teddy Swims - I Can't Make You Love Me",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "_Bm14Bv1DKU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=_Bm14Bv1DKU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 18'
  },
  {
    image: 'https://i.ytimg.com/vi/7w4RUwVPkv0/hqdefault.jpg',
    imageText: "폴킴(Paul Kim) - 우리 만남이",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "76GMyR0W_Gk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=76GMyR0W_Gk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2020. 4. 22'
  },
  {
    image: 'https://i.ytimg.com/vi/ojsj6yuSRHU/hqdefault.jpg',
    imageText: "Musiq soulchild - today",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "P_5Ai1cM9No",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=P_5Ai1cM9No',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 11. 29'
  },
  {
    image: 'https://i.ytimg.com/vi/Gru4IfbKlfU/hqdefault.jpg',
    imageText: "Bobby Caldwell - What You Won't Do for Love",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "rp2RnAXhY8g",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=rp2RnAXhY8g',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 8. 20'
  },
  {
    image: 'https://i.ytimg.com/vi/MVITXvCuqeU/maxresdefault.jpg',
    imageText: "Shawn Mendes - If I Can't Have You",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "oTJ-oqwxdZY",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=oTJ-oqwxdZY',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 5. 3'
  },
  {
    image: 'https://i.ytimg.com/vi/97Fi7v_H7k4/maxresdefault.jpg',
    imageText: "Bumkey - Attraction (갖고놀래) (feat.Dynamic Duo (다이나믹 듀오)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "zHd1JcExu1k",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=zHd1JcExu1k',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2014. 11. 8'
  },
  {
    image: 'https://i.ytimg.com/vi/pC6tPEaAiYU/maxresdefault.jpg',
    imageText: "HYUKOH(혁오) - TOMBOY",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "pC6tPEaAiYU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=pC6tPEaAiYU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 4. 24'
  },
  {
    image: 'https://i.ytimg.com/vi/j5g5QbX7QO4/maxresdefault.jpg',
    imageText: "우디 [Woody] - 이 노래가 클럽에서 나온다면 [Fire Up] 가사",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "zOWq1GAnvuM",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=zOWq1GAnvuM',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 1. 27'
  },
  {
    image: 'https://i.ytimg.com/vi/fjL3Sjm8CDU/maxresdefault.jpg',
    imageText: "기리보이 (Giriboy) - 교통정리 (Feat. 헤이즈)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "fjL3Sjm8CDU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=fjL3Sjm8CDU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 5. 21'
  },
  {
    image: 'https://i.ytimg.com/vi/L7L7aSeAZ4E/maxresdefault.jpg',
    imageText: "기리보이 (Giriboy) - 이혼서류",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "0Remc4lR92o",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=0Remc4lR92o',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 11'
  },
  {
    image: 'https://kpopeasy.com/wp-content/uploads/2019/07/camping-everywhere.jpg',
    imageText: "죠지(george) - camping everywhere",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "4UF-5DPvBDQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=4UF-5DPvBDQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 7. 15'
  },
  {
    image: 'https://i.ytimg.com/vi/nG6249LQEkU/hqdefault.jpg',
    imageText: "[DF Killing Voice] george 죠지",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "nG6249LQEkU",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=nG6249LQEkU',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 7. 12'
  },
  {
    image: 'https://i.ytimg.com/vi/ZBtJPKokA-k/hqdefault.jpg',
    imageText: "기리보이 - 증오 (Feat. 안병웅) [치명적인 앨범 Ⅲ]",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "ZlC9nVb-72I",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=ZlC9nVb-72I',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 12. 2'
  },
  {
    image: 'https://images.genius.com/1fd6a2e62ed6ac997f01d5714aed9474.1000x1000x1.jpg',
    imageText: "기리보이 - 술자리",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "6KlBEHB6lBg",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=6KlBEHB6lBg',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2018. 11. 25'
  },
  {
    image: 'https://image.bugsm.co.kr/album/images/500/202762/20276214.jpg',
    imageText: "그루비룸 (GroovyRoom), 릴러말즈 (Leellamarz) - 염색 (Feat. 유라(youra))",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "dPEXF9pmdQ4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=dPEXF9pmdQ4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 9'
  },
  {
    image: 'https://i.ytimg.com/vi/Xzf9iNiaRX0/maxresdefault.jpg',
    imageText: "GROOVYROOM X LEELLAMARZ - 도시 생활 (City Life) Official Video",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "Xzf9iNiaRX0",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=Xzf9iNiaRX0',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 9. 20'
  },
  {
    image: 'https://image.bugsm.co.kr/album/images/500/201152/20115259.jpg',
    imageText: "Hoody (후디) - 한강 (HANGANG)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "9upHfoQh1K4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=9upHfoQh1K4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 8. 31'
  },
  {
    image: 'https://image.genie.co.kr/Y/IMAGE/IMG_ALBUM/080/902/435/80902435_1481102515367_1_600x600.JPG',
    imageText: "Hoody (후디) - By Your Side (Feat. Jinbo)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "TrxRuAOpHXQ",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=TrxRuAOpHXQ',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2016. 12. 8'
  },
  {
    image: 'https://i.ytimg.com/vi/uUt4lwddk8U/hqdefault.jpg',
    imageText: "Zion.T (자이언티) - 눈 (Feat. 이문세)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "uUt4lwddk8U",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=uUt4lwddk8U',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2017. 12. 4'
  },
  {
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AAJQU03.img?h=0&w=720&m=6&q=60&u=t&o=f&l=f',
    imageText: "Zion.T (자이언티) - 5월의 밤",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "Ug-x9fZjESk",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=Ug-x9fZjESk',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 11. 6'
  },
  {
    image: 'https://image.bugsm.co.kr/album/images/500/202394/20239451.jpg',
    imageText: "장범준 - 당신과는 천천히",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "-wwuoWFmgq4",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=-wwuoWFmgq4',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2019. 3. 21'
  },
  {
    image: 'https://i.ytimg.com/vi/6dggc7qqKUo/maxresdefault.jpg',
    imageText: "Brushy One String | Chicken in The Corn (Lyrics)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "6dggc7qqKUo",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=6dggc7qqKUo',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2015. 3. 31'
  },
  {
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5GwkhKGMsHpN8SCRGzfFYEPRuhdtKlLcFHiQ2zJkxFGyYaFSR&usqp=CAU',
    imageText: "Brushy One String | DESTINY (Lyrics)",
    backBtnType: 'w',
    content: [
      {
        type: 'youtube',
        data: "KC2r4VnmD2E",
        desc: ''
      },
      {
        type: 'text',
        data: '출처 https://www.youtube.com/watch?v=KC2r4VnmD2E',
        desc: ''
      },
    ],
    origin: 'youtube',
    date: '2014. 8. 27'
  },
];

exports.post = post;
